# Generated by Django 5.1.6 on 2025-02-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('pn', models.IntegerField(default=1234567890, max_length=10)),
                ('pass_wrd', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
