# Generated by Django 5.2.1 on 2025-06-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_acc',
            name='pn',
            field=models.IntegerField(default=1234567890),
        ),
    ]
